services:
  # rodei ALTER USER postgres WITH PASSWORD 'postgres';
  # dentro do docker para a imagem funcionar corretamente
  pg:
    image: leogloriainfnet/postgres-tp2-spring:2.0-mac
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  guilda-es:
    image: leogloriainfnet/elastic-tp2-spring:1.0-windows
    container_name: guilda-es-at
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
