spring.application.name=tp1 
spring.datasource.url=jdbc:postgresql://localhost:5432/tp2_db
spring.datasource.username=usuario
spring.datasource.password=senha
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
